import { Link } from "react-router-dom";
import { FileText, ArrowLeft } from "lucide-react";
import Seo from "../components/Seo";

const SECTIONS = [
  {
    title: "1. Accepting these terms",
    body: `By creating an account or using Skill2Career, you agree to these terms. If you don't agree, please don't use the platform.`,
  },
  {
    title: "2. Your account",
    body: `You're responsible for keeping your login credentials secure and for all activity under your account. Provide accurate information when creating your profile — job seekers and recruiters both rely on that accuracy to make good decisions.`,
  },
  {
    title: "3. Acceptable use",
    body: `Don't post false job listings, misrepresent your qualifications, scrape the platform, attempt to bypass rate limits or security controls, or use the platform to harass other users. We may suspend or terminate accounts that violate these terms.`,
  },
  {
    title: "4. Content you submit",
    body: `You retain ownership of your resume, profile, and any content you submit. By submitting it, you grant us permission to store and display it as needed to operate the platform (e.g. showing your application to a recruiter you applied to).`,
  },
  {
    title: "5. Job postings & applications",
    body: `Recruiters are responsible for the accuracy of their job postings. Skill2Career is a matching platform — we don't guarantee employment outcomes, interview results, or hiring decisions, which remain solely between job seekers and recruiters.`,
  },
  {
    title: "6. AI-powered features",
    body: `Mock interview and assessment scores, and ATS resume scores, are generated by automated tools intended to help you practice and improve. They're guidance, not a guarantee of real interview or hiring outcomes.`,
  },
  {
    title: "7. Termination",
    body: `You may delete your account at any time. We may suspend accounts that violate these terms or misuse the platform.`,
  },
  {
    title: "8. Changes to these terms",
    body: `We may update these terms occasionally. Continued use of the platform after changes means you accept the updated terms.`,
  },
];

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-white text-ink">
      <Seo
        title="Terms of Service"
        description="The terms governing your use of Skill2Career."
        path="/terms"
      />

      <div className="max-w-2xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <Link to="/" className="inline-flex items-center gap-1.5 text-sm font-medium text-ink/60 hover:text-ink transition-colors mb-8">
          <ArrowLeft className="w-4 h-4" /> Back to home
        </Link>

        <div className="w-12 h-12 rounded-2xl bg-pine/8 border border-pine/20 flex items-center justify-center mb-5">
          <FileText className="w-5.5 h-5.5 text-pine" />
        </div>

        <h1 className="font-display text-3xl font-bold text-ink mb-2">Terms of Service</h1>
        <p className="text-sm text-ink/40 mb-10">Last updated: {new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}</p>

        <div className="space-y-8">
          {SECTIONS.map((s) => (
            <section key={s.title}>
              <h2 className="font-display text-base font-bold text-ink mb-2">{s.title}</h2>
              <p className="text-sm text-ink/60 leading-relaxed">{s.body}</p>
            </section>
          ))}
        </div>

        <div className="mt-12 pt-8 border-t border-mist">
          <p className="text-sm text-ink/50">
            Questions about these terms?{" "}
            <Link to="/contact" className="text-pine font-semibold hover:underline">
              Contact us
            </Link>.
          </p>
        </div>
      </div>
    </div>
  );
}
